imanuelcimahi_site/imanuelcimahi_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('events/', include('events.urls')),
    path('unitmisioner/', include('unit_misioner.urls')),
    path('photo-gallery/', include('photo_gallery.urls')),
    path('phmj/', include('phmj.urls')),
    path('wartajemaat/', include('jadwal_pelayanan.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

imanuelcimahi_site/phmj/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.AnggotaPhmjView, name='anggota-phmj'),
]

imanuelcimahi_site/unit_misioner/urls.py
from django.urls import path
from .views import DepartmentListView, DepartmentDetailView

app_name = 'unit_misioner'

urlpatterns = [
    path('', DepartmentListView.as_view(), name='department-list'),
    path('departments/<slug:slug>/', DepartmentDetailView.as_view(), name='department-detail'),
]

imanuelcimahi_site/unit_misioner/models.py
from django.db import models
from django.utils.text import slugify

class Department(models.Model):
    name = models.CharField(max_length=100)
    singkatan = models.CharField(max_length=50)
    description = models.TextField()
    logo = models.ImageField(upload_to='department_logo/', blank=True, null=True)
    banner = models.ImageField(upload_to='department_banners/', blank=True, null=True)
    slug = models.SlugField(unique=True, max_length=100)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name
    
    def get_custom_order(self):
        custom_order = {
            'pklu': 1,
            'pkb': 2,
            'pkp': 3,
            'gp': 4,
            'pt': 5,
            'pa': 6,
            'peg': 7,
            'muger': 8,
            'inforkom': 9,
            'pelkes': 10,
            'teologi': 11,
            'kedukaan': 12,
            'rumahtangga': 13,
        }
        return custom_order.get(self.singkatan, 0)


class Position(models.Model):
    title = models.CharField(max_length=100)

    def __str__(self):
        return self.title

class Member(models.Model):
    name = models.CharField(max_length=100)
    department = models.ForeignKey(Department, on_delete=models.CASCADE)
    position = models.ForeignKey(Position, on_delete=models.CASCADE)
    photo = models.ImageField(upload_to='member_photos/', blank=True, null=True)
    

    def __str__(self):
        return self.name

imanuelcimahi_site/unit_misioner/views.py
from django.views.generic import DetailView, ListView
from .models import Department

class DepartmentListView(ListView):
    model = Department
    template_name = 'unit_misioner/department_list.html'
    context_object_name = 'departments'

    def get_queryset(self):
        departments = super().get_queryset()
        return sorted(departments, key=lambda department: department.get_custom_order())
    

class DepartmentDetailView(DetailView):
    model = Department
    template_name = 'unit_misioner/department_detail.html'
    context_object_name = 'department'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['members'] = self.object.member_set.all()
        return context

imanuelcimahi_site/unit_misioner/templates/unit_misioner/department_detail.html
{% extends 'base.html' %}

{% block department_detail %}
  <h1>{{ department.name }}</h1>
  <p>{{ department.description }}</p>
  <img src="{{ department.banner.url }}" alt="{{ department.name }} Banner">

  <h2>Pengurus</h2>
  <ul>
    {% for member in members %}
      <li>
        {{ member.position }} : {{ member.name }} 
        {% if member.photo %}
          <img src="{{ member.photo.url }}" alt="{{ member.name }} Photo">
        {% endif %}
      </li>
    {% endfor %}
  </ul>
{% endblock %}

imanuelcimahi_site/unit_misioner/templates/unit_misioner/department_list.html
{% extends 'base.html' %}

{% block content_list %}
  <h1>Departments</h1>
  <ul>
    {% for department in departments %}
      <li><a href="{% url 'unit_misioner:department-detail' department.slug %}">{{ department.name }}</a></li>
    {% endfor %}
  </ul>
{% endblock %}