imanuelcimahi_site/imanuelcimahi_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('events/', include('events.urls')),
    path('unitmisioner/', include('unit_misioner.urls')),
    path('photo-gallery/', include('photo_gallery.urls')),
    path('phmj/', include('phmj.urls')),
    path('wartajemaat/', include('jadwal_pelayanan.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

imanuelcimahi_site/jadwal_pelayanan/urls.py
from django.urls import path
from . import views

app_name = 'jadwal_pelayanan'

urlpatterns = [
    path('service-list/', views.service_list, name='service-list'),
    path('service-details/<int:service_id>/', views.service_details, name='service-details'),
]

imanuelcimahi_site/phmj/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.AnggotaPhmjView, name='anggota-phmj'),
]

imanuelcimahi_site/jadwal_pelayanan/models.py
from django.db import models
from django.utils import timezone

class Individual(models.Model):
    name = models.CharField(max_length=300)

    def __str__(self):
        return self.name

class Role(models.Model):
    title = models.CharField(max_length=50)
    
    def __str__(self):
        return self.title
    

class Service(models.Model):
    datetime = models.DateTimeField()
    dresscode = models.CharField(max_length=50, null=True, blank=True)
    place = models.CharField(max_length=100, null=True, blank=True)
    roles = models.ManyToManyField(Role, through='ServiceRole')

    def __str__(self):
        local_datetime = timezone.localtime(self.datetime)
        return f"{local_datetime.strftime('%d-%m-%Y %H:%M:%S')} - {self.place}"
    


class ServiceRole(models.Model):
    service = models.ForeignKey(Service, on_delete=models.CASCADE)
    role = models.ForeignKey(Role, on_delete=models.CASCADE)
    person = models.ForeignKey(Individual, on_delete=models.CASCADE)

    def __str__(self):
        local = timezone.localtime(self.service.datetime)
        return f"{local.strftime('%d-%m-%Y %H:%M:%S')} - {self.role.title} - {self.person.name} - {self.service.place} - {self.service.dresscode}"

imanuelcimahi_site/jadwal_pelayanan/views.py
from django.shortcuts import render, get_object_or_404
from .models import Service

def service_list(request):
    services = Service.objects.all()
    context = {
        'services': services,
    }
    return render(request, 'jadwal_pelayanan/service_list.html', context)

def service_details(request, service_id):
    service = get_object_or_404(Service, pk=service_id)
    context = {
        'service': service,
    }
    return render(request, 'jadwal_pelayanan/service_details.html', context)

imanuelcimahi_site/jadwal_pelayanan/templates/jadwal_pelayanan/service_details.html
{% extends 'inner_page.html' %}

{% block service_detail %}
<section id="portfolio" class="portfolio"
    x-data="{tag: 'Semua', photos: []}"
    x-init="photos = await (await fetch('photogallerylist')).json()">
   
    <div class="container" data-aos="fade-up">
        <div class="section-title">
            <h2>List Petugas Pelayan Hari Minggu</h2>
            <p>Informasi Jadwal Pelayanan</p>
        </div>
        <div class="container mt-5"></div>
            {% if service %}
                <p><strong>Tanggal dan Jam:</strong> {{ service.datetime }}</p>
                <p><strong>Dress Code:</strong> {{ service.dresscode }}</p>
                <p><strong>Tempat:</strong> {{ service.place }}</p>
                
                <h2>Role Details</h2>
                <table>
                    <tr>
                        <th>Role</th>
                        <th>Person</th>
                    </tr>
                    {% for service_role in service.servicerole_set.all %}
                    <tr>
                        <td>{{ service_role.role.title }}</td>
                        <td>{{ service_role.person.name }}</td>
                    </tr>
                {% endfor %}
                </table>
                {% else %}
                <p>Service not found.</p>
            {% endif %}
        </div>      
    </div>
</section>        
{% endblock service_detail %}

imanuelcimahi_site/jadwal_pelayanan/templates/jadwal_pelayanan/service_list.html
{% extends 'base.html' %}

{% block service_list %}
<section id="portfolio" class="portfolio"
    x-data="{tag: 'Semua', photos: []}"
    x-init="photos = await (await fetch('photogallerylist')).json()">
   
    <div class="container" data-aos="fade-up">
        <div class="section-title">
            <h2>List Pelayanan Ibadah Hari Minggu </h2>
            <p>Informasi Jadwal Pelayanan</p>
        </div>
      
        <ul>
            {% for service in services %}
                <li>
                    <a href="{% url 'jadwal_pelayanan:service-details' service.id %}">
                        {{ service.datetime }} - {{ service.place }} - {{ service.dresscode }}
                    </a>
                </li>
            {% endfor %}
        </ul>
    </div>
</section>
{% endblock service_list %}